config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'items#index'
  
  resources :users, only: :new
  resources :items

  resources :mypage, only: [:index] do
    collection do
      get 'logout'
    end
  end

  resources :cards, only: [:index, :new, :create, :destroy] do
    member do
      get 'confirmation'
      post 'pay'
      get 'complete'
    end
  end

  resources :categories, only: [:index, :show]
  resources :brands
  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates :first_name, :last_name, :first_name_kana, :post_cord, :city, :address, presence: true

  validates_format_of :last_name, :first_name, with: /\A[一-龥ぁ-ん]/, message: "全角で入力してください"
  validates_format_of :last_name_kana, :first_name_kana, with: /\A[ぁ-んー－]+\z/, message: "全角かなで入力してください"
  validates_format_of :post_cord, with: /\A\d{7}\z/, message: "7桁の半角数字を入力してください"
  validates_format_of :city, with: /\A[一-龥]+\z/, message: "全角漢字で入力してください"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
  has_many :genres, through: :brand_genres
  has_many :brand_genres
end

app/models/brands_genre.rb
class BrandsGenre < ApplicationRecord
  belongs_to :brand, optional: true
  belongs_to :genre, optional: true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates  :customer_id, :card_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :text, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :brands,through: :brand_genres
  has_many :brand_genres
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  # belongs_to :user
  belongs_to :seller, class_name: 'User', foreign_key: 'seller_id'
  belongs_to :buyer, class_name: 'User', foreign_key: 'buyer_id', optional: true

  belongs_to :category
  belongs_to :brand, optional: true
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  # item_imagesモデルの属性付
  has_many :item_images, inverse_of: :item, dependent: :destroy
  accepts_nested_attributes_for :item_images ,allow_destroy: true


  validates :name, presence: true, length: { maximum: 40 }
  validates :text, presence: true, length: { maximum: 1000 }
  validates :condition, :shipping_method, :shipping_days, :prefecture_id, :shipping_price, :price, :seller_id, :sale_status, presence: true
  validates :price, presence: true, inclusion: 300..9999999

  def self.search(search)
    if search
      Item.where('text LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  belongs_to :item, optional: true

  mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer, class_name: 'User'
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  # has_many :items, dependent: :destroy
  has_many :buyer_items, class_name: 'Item', foreign_key: 'buyer_id', dependent: :destroy
  has_many :seller_items, class_name: 'Item', foreign_key: 'seller_id', dependent: :destroy
  
  # has_many :messages, dependent: :destroy
  has_many :buyer_messages, class_name: 'Message', foreign_key: 'buyer_id', dependent: :destroy
  has_many :seller_messages, class_name: 'Message', foreign_key: 'seller_id', dependent: :destroy

  has_one :address, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :card
  has_many :sns_credentials

  validates :nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthyear, :birthmonth, :birthday, :telephone, presence: true

  validates_format_of :password, with: /([0-9].*[a-zA-Z]|[a-zA-Z].*[0-9])/, message: "７文字以上の英数混在で入力してください。"
  validates_format_of :last_name, :first_name, with: /\A[一-龥ぁ-ん]/, message: "全角で入力してください"
  validates_format_of :last_name_kana, :first_name_kana, with: /\A[ぁ-んー－]+\z/, message: "全角かなで入力してください"
  validates_format_of :telephone, with: /\A\d{11}\z/, message: "11桁の半角数字を入力してください"
  validates_format_of :birthyear, with: /\A\d{4}\z/, message: "4桁の半角数字を入力してください"
  validates_format_of :birthmonth, :birthday, with: /\A[0-9]+\z/, message: "半角数字を入力してください"

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  has_one :card
  has_many :cards
  has_many :items

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]

  def index
    @products = Item.includes(:item_images).order(updated_at: "DESC").limit(3)
  end

  def new
    @item = Item.new
    @item.item_images.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      redirect_to new_item_path
    end
  end

  def show
    @images = @item.item_images.limit(4)
  end

  def edit
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      redirect_to edit_item_path(@item.id)
    end
  end



  private

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end

  def item_params
    params.require(:item).permit(:name, :size, :condition, :shipping_method, :shipping_days, :prefecture_id, :shipping_price, :price, :text, :category_id, :brand_id, :seller_id, :buyer_id, :sale_status, item_images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id)
  end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  def new
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_aside.html.haml
%aside.appBanner
  .appBanner-contents
    %h2.appBanner-contents__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.appBanner-contents__text
      今すぐ無料ダウンロード！
    .appBanner-contents__btn
      = link_to "#", class: "appStoreBtn" do
        = image_tag 'logo/app-store.svg'
      = link_to "#", class: "googlePlayBtn" do
        = image_tag 'logo/google-play.svg'

app/views/items/_footer.html.haml
%footer
  %ul.footer-texts
    %li.footer-texts__content
      %h2.footer-texts__content-title
        FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社）", "#"
        %li
          = link_to "プライバシーポリシー", "#"
        %li
          = link_to "FURIMA利用規約", "#"
        %li
          = link_to "ポイントに関する特約", "#"
    %li.footer-texts__content
      %h2.footer-texts__content-title
        FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧", "#"
        %li
          = link_to "ブランド一覧", new_brand_path
    %li.footer-texts__content
      %h2.footer-texts__content-title
        ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド", "#"
        %li
          = link_to "FURIMAロゴ利用ガイドライン", "#"
        %li
          = link_to "お知らせ", "#"
  .footer-logo
    = link_to root_path do
      = image_tag 'logo/logo-white.png'
  %p © FURIMA
= link_to new_item_path do
  .sellBtn
    %span.sellBtn__text 出品する
    = image_tag 'icon/icon_camera.png', class:"sellBtn__icon"

app/views/items/_header.html.haml
%header.top-header
  .header-contents
    .header-contents__main
      %h1.header-contents__main-icon
        = link_to root_path  do
          = image_tag 'logo/logo.png'
      .header-contents__main-searchBox
        = form_with(method: :get) do |form|
          = form.text_field :key, id:"serchInput", class:"searchBox-input", placeholder:"キーワードから探す"
          = form.submit class:"searchBox-btn"
    .header-contents__bottom
      %ul.hcBottom__left
        %li
          = link_to "#", class: "category__search search__btn" do
            = fa_icon("bars")
            カテゴリーから探す
          %ul.category__parent.category__list
            - @parents.each do |parent|
              %li
                = link_to "#", class: "category__parent--name" do
                  = parent.name
                %ul.category__child.category__list
                  - parent.children.each do |child|
                    %li
                      = link_to "#", class: "category__child--name" do
                        = child.name
                      %ul.category__grandchild.category__list
                        - child.children.each do |grandchild|
                          %li
                            = link_to "#", class: " category__child--name" do
                              = grandchild.name 
            = link_to categories_path, class: "category__parent--name" do
              カテゴリー一覧

      %ul.hcBottom__left
        = link_to "#", id: "brandBtn" do
          = fa_icon("tag")
          ブランド
        %ul.category__parent.brands
          - @brands.each do |brand| 
            %li
              = link_to "#", class:"category__parent--name" do
                = brand.name
      %ul.hcBottom__right
        - if user_signed_in?
          %li.hcBottom__right--session
            = link_to current_user.nickname, mypage_index_path
          %li.hcBottom__right--registration
            = link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          %li.hcBottom__right--session
            = link_to "ログイン",  new_user_session_path
          %li.hcBottom__right--registration
            = link_to "新規会員登録", new_user_path

app/views/items/_itemnav.html.haml
%nav.items__navbar
  %ul.item__navbar__content
    %li= link_to "FURIMA", root_path
    %li= fa_icon("angle-right")
    %li= link_to "ベビー・キッズ", root_path
    %li= fa_icon("angle-right")
    %li= link_to "ベビー服（男女兼用）〜95cm", root_path
    %li= fa_icon("angle-right")
    %li= link_to "アウター", root_path

app/views/items/edit.html.haml
= form_for @item do |f|

  .main__items
    .user-sign__up
      .header_logo
        = link_to root_path  do
          = image_tag 'logo/logo.png'
    .sell-form
      .sell-form__image
        .sell-form__image__box
          %label.image-product 出品画像
          %span.image-attention 必須
          %p.image-content 最大10枚までアップロードできます
          #image-box
            #previews
              - if @item.persisted?
                - @item.item_images.each_with_index do |image, i|
                  .preview
                    = image_tag "#{image.image}", data: { index: i}, width: "100", height: '100'
                    %label{for: "camera"}
                      = fa_icon("camera", "data-edit-id":"#{i}")
                    %span.js-remove-edit{"data-edit-id":"#{i}"}
                      削除
            = f.fields_for :item_images do |image|
              .js-file_group{"data-index" => "#{image.index}"}
                = image.file_field :image, class: 'js-file', style: "display:none"
                -# %span.js-remove 削除
              - if @item.persisted?
                = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
            - if @item.persisted?
              .js-file_group{"data-index" => "#{@item.item_images.count}"}
                = file_field_tag :image, name: "item[item_images_attributes][#{@item.item_images.count}][image]", class: "js-file[#{@item.item_images.count}]", style:"display:none"
                -# .js-remove 削除

      .sell-form__product
        .sell-form__product__box
          .sell-form__product__box-top
            %label.product-name 商品名
            %span.name-attention 必須
            = f.text_field :name, class: 'product-input', placeholder: "40文字以内"
          .sell-form__product__box-bottom
            %label.product-explanation 商品の説明
            %span.name-attention 必須
            = f.text_area :text, class: "explanation-input", placeholder: "商品の説明(必須1,000文字以内) (色、素材、重さ、低下、注意点など) 例)2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでおすすめです。"

      .sell-form__detail
        .sell-form__detail__box
          %label.sell-form__detail__box-name 商品の詳細
          .sell-form__detail__box-top
            %label.detail-category カテゴリー
            %span.detail-attention 必須
            = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: '選択して下さい'}, {class: 'new-contentsboxselect__input', id: 'category-select-parent', required: "required"}
          .sell-form__detail__box-top
            %label.detail-brand ブランド
            %span.detail-attention__any 任意
            = f.collection_select :brand_id, Brand.all, :id, :name, {prompt: "選択してください"}, {class: 'new-contentsboxselect__input', id: 'category-select-parent'}
          .sell-form__detail__box-bottom
            %label.detail-condition 商品の状態
            %span.detail-attention 必須
            = f.select :condition, ["選択してください", "新品、未使用", "未使用に近い", "目立った傷や汚れなし", "やや傷や汚れあり", "傷や汚れあり", "全体的に状態が悪い"], class: "item_condition"


      .sell-form__delivery
        .sell-form__delivery__box
          %label.sell-form__delivery__box-name 配送について
          .sell-form__delivery__box-top
            %label.delivery-burden 配送料の負担
            %span.delivery-attention 必須
            = f.select :shipping_price, ["送料込み(出品者負担)", "着払い(購入者負担)"], include_blank: '選択してください', class: "item-input__select"

          .sell-form__delivery__box-middle
            %label.delivery-area 発送元の地域
            %span.delivery-attention 必須
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "選択してください", class: "item-input__select"

          .sell-form__delivery__box-bottom
            %label.delivery-days 発送までの日数
            %span.delivery-attention 必須
            = f.select :shipping_days, ["1~2日で発送", "2~3日で発送", "4~7日で発送"], include_blank: '選択してください', class: "item-input__select"

          .sell-form__delivery__box-method
            %label.delivery-method 配送方法
            %span.delivery-attention 必須
            = f.select :shipping_method, ["未定", "らくらくフリマ便", "ゆうメール", "レターパック", "普通郵便(定形、定形外)", "クロネコヤマト", "ゆうパック", "クリックポスト", "ゆうパケット"], include_blank: '選択してください', class: "item-input__select"

      .sell-form__price
        .sell-form__price__box
          %label.sell-form__price__box-name 価格（¥300～9,999,999）
          .sell-form__price__box-top
            .sell-form__price__box-top--input
              %label.selling-price 販売価格
              %span.price-attention 必須
              %span.price-yen ¥
              = f.text_field :price, class: "price-input", placeholder: "例）500"
            .sell-form__price__box-top--fee
              .selling-fee 販売手数料（10%）
              %span.selling-fee__zero ー

            %hr.border
              .sell-form__price__box-top--profit
                .selling-profit 販売利益
                %span.selling-profit__zero ー

            .sell-form__price__box-middle
              .sell-form__price__box-middle__sell--btn
                = f.submit "情報を更新する", class: "sell-btn"

              .back-btn
                = link_to "もどる", root_path

            .sell-form__price__box-bottom
              %p.rule 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。

app/views/items/index.html.haml
= render partial: "items/header"
.topContents
  %section.mainVisual
    .mvContent
      %h2.mvContent__title
        %br/
        人生を変えるフリマアプリ
      %p.mvContent__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br>/
        フリマアプリです
      .mvContent__btn
        = link_to "#", class: "appStoreBtn" do
          = image_tag 'logo/app-store.svg'
        = link_to "#", class: "googlePlayBtn" do
          = image_tag 'logo/google-play.svg'
  %section.pict-reason
    %h2.pict-reason__title
      FURIMAが選ばれる3つの理由
    %ul.pict-reason__lists
      %li.prList
        .prList__image
          %span.prList__image--number 1
          = image_tag 'pict/pict-reason-01.jpg'
        %h3.prList__title
          %span 3分
          ですぐに出品
        %p.prList__text
          スマホで入力するだけで簡単に出品できる！
      %li.prList
        .prList__image
          %span.prList__image--number 2
          = image_tag 'pict/pict-reason-02.jpg'
        %h3.prList__title
          %span シンプル
          で使いやすい
        %p.prList__text
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.prList
        .prList__image
          %span.prList__image--number 3
          = image_tag 'pict/pict-reason-03.jpg'
        %h3.prList__title
          手数料
          %span 業界最安
        %p.prList__text
          最大3%でお得に出品&amp;購入！
  %section.topMiddleDl
    .topMiddleDl-content
      %h2.topMiddleDl-content__title 会員数日本一位
      %p.topMiddleDl-content__text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .topMiddleDl-content__btn
        = link_to "#" do
          = image_tag 'logo/app-store.svg', class:"appStoreBtn"
        = link_to "#", class: "googlePlayBtn" do
          = image_tag 'logo/google-play.svg'
  %section.features
    %h2.features__title
      FURIMAの特徴
    .features__contents
      %section.ftContent
        %figure.ftContent__img
          = image_tag 'icon/icon-01.png'
        %h3.ftContent__title
          簡単に売り買いできる
        %p.ftContent__text
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.ftContent
        %figure.ftContent__img
          = image_tag 'icon/icon-03.png'
        %h3.ftContent__title
          売上金は即日振り込みに対応
        %p.ftContent__text
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      %section.ftContent
        %figure.ftContent__img
          = image_tag 'icon/icon-04.png'
        %h3.ftContent__title
          様々な支払いに対応
        %p.ftContent__text
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickup
    %h2.pickup__title
      ピックアップカテゴリー
    .pickup-contents
      .pickup-contents__head
        = link_to "#" do
          %h3.pickup-contents__head-title 新規投稿商品
      .pickup-products
        - @products.each do |item|
          .pickup-products__item
            = link_to "/items/#{item.id}" do
              %figure.pickup-products__item-img
                = image_tag item.item_images.first&.image.url
              .pickup-products__item-content
                %h3.pickup-products__item-content--name
                  = item.name
                .pickup-products__item-content--detail
                  %ul
                    %li 
                      = item.price.to_s(:delimited)
                      円
                    %li
                      = fa_icon("star")
                      0
                  %p (税込)
              - if item.buyer_id.present?
                .sold-out__mask
                  = image_tag 'pict/sold_out.png'
  %section.pickup
    %h2.pickup__title
      ピックアップブランド
    .pickup-contents
      .pickup-contents__head
        = link_to "#" do
          %h3.pickup-contents__head-title アーカイバ
      .pickup-products
        .pickup-products__item
          = link_to 'http://furima.tokyo/products/3' do
            %figure.pickup-products__item-img
              = image_tag 'pict/a007.png'
            .pickup-products__item-content
              %h3.pickup-products__item-content--name product3
              .pickup-products__item-content--detail
                %ul
                  %li 30000円
                  %li
                    = fa_icon("star")
                    0
                %p (税込)
        .pickup-products__item
          = link_to 'http://furima.tokyo/products/2' do
            %figure.pickup-products__item-img
              = image_tag 'pict/a004.png'
            .pickup-products__item-content
              %h3.pickup-products__item-content--name product2
              .pickup-products__item-content--detail
                %ul
                  %li 20000円
                  %li
                    = fa_icon("star")
                    0
                %p (税込)
        .pickup-products__item
          = link_to 'http://furima.tokyo/products/1' do
            %figure.pickup-products__item-img
              = image_tag 'pict/a001.png'
            .pickup-products__item-content
              %h3.pickup-products__item-content--name product1
              .pickup-products__item-content--detail
                %ul
                  %li 10000円
                  %li
                    = fa_icon("star")
                    0
                %p (税込)
= render partial: "items/aside"
= render partial: "items/footer"

app/views/items/show.html.haml
= render partial: "items/header"
- breadcrumb :show
= render "layouts/breadcrumbs"

.main
  .show__main
    .show__main__content
      .show__main__content__top
        %h2.show__main__content__top__name 
          = @item.name
        .show__main__content__top__image
          - if @item.buyer_id.blank?
            %ul.maincontent__image
              %li= image_tag @images[0].image.url
            %ul.subcontent__image
              - @images.drop(1).each do |image|
                %li
                  = image_tag image.image.url
          - else
            = image_tag 'pict/sold_out.png', class: "maincontent__image"
        .show__main__content__price
          %span
            = "¥#{@item.price.to_s(:delimited)}"
          .show__main__content__price__detail
            %span （税込） 
            %span 送料込み
        .show__main__content__detail
          = @item.text
        .show__main__content__table
          %table
            %tbody
              %tr
                %th 出品者
                %td= @item.seller.nickname
              %tr
                %th カテゴリー
                %td
                  =link_to @item.category.name, '#'
              %tr
                %th ブランド
                -if @item.brand ==! nil
                  %td=@item.brand.name
                - else
                  %td="ブランドの指定はありません" 
              %tr
                %th 商品のサイズ
                - if @item.size ==! nil
                  %td=@item.size
                -else
                  %td="サイズ指定はありません"
              %tr
                %th 商品の状態
                %td
                  = @item.condition
              %tr
                %th 配送料の負担
                - if @item.shipping_price ==! 0
                  %td= @item.shipping_price
                -else
                  %td= "配送料の負担はありません"
              %tr
                %th 発送元の地域
                %td=@item.prefecture.name
              %tr
                %th 発送日の目安
                %td 
                  = @item.shipping_days
        .show__main__content__option        
          %ul
            %li.option__btn#like__btn
              = fa_icon("star")
              =link_to 'お気に入り 225', '#'
          %ul.optional
            %li.optional__btn
              = fa_icon("flag")
              = link_to '不適切な商品の通報', '#'
        - if @item.buyer_id.present?
          %button.show__main__content__sold-out{disabled:""} SOLD OUT
        - elsif user_signed_in? == false
          = link_to "ログインして下さい", user_session_path, class:"show__main__content__purchase-btn"
        - elsif current_user.id == @item.seller_id
          .show__main__content__btn
            = link_to "編集する", edit_item_path(@item.id), class:"show__main__content__btn--edit"
            = link_to "削除する", item_path(@item.id), method: :delete, class:"show__main__content__btn--delete"
        - else
          = link_to "購入画面に進む", confirmation_card_path(@item.id), class:"show__main__content__purchase-btn"
      .show__main__content__comment
        %textarea#comment_body{name: "comment[body]", required: "required"}
        %p.comment__message 
          相手のことを考え丁寧なコメントを心がけましょう。
          %br 
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %br
        %button.commentBtn{name: "button", type: "submit"}
          =fa_icon("comment")
          コメントする
      .show__main__content__links
        %ul.links
          %li.links__left
            = fa_icon("angle-left")
            =link_to "前の商品", '#'
          %li.links__right
            = fa_icon("angle-right")
            =link_to "次の商品", '#'
      .show__main__content__items
        =link_to "ベビー・キッズをもっと見る", '#'




= render partial: "items/aside"
= render partial: "items/footer"