config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'items#index'
  
  resources :users, only: :new
  resources :items

  resources :mypage, only: [:index] do
    collection do
      get 'logout'
    end
  end

  resources :cards, only: [:index, :new, :create, :destroy] do
    member do
      get 'confirmation'
      post 'pay'
      get 'complete'
    end
  end

  resources :categories, only: [:index, :show]
  resources :brands
  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  validates  :customer_id, :card_id, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"

  before_action :set_card
  before_action :set_key, only: [:index, :create, :destroy, :confirmation]
  before_action :retrieve_card, only: [:index, :confirmation]
  before_action :set_item, only: [:confirmation, :pay, :complete]

  def index
  end

  def new
    card = Card.find_by(user_id: current_user.id)
    redirect_to action: :index if card.present?
  end

  def create
    if params['payjp_token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(card: params['payjp_token'])
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to mypage_index_path
      else
        redirect_to action: "create"
      end
    end
  end


  def destroy
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete
    if @card.destroy
      redirect_to action: :new
    else
      redirect_to action: :index
    end
  end

  def confirmation
    redirect_to user_session_path unless user_signed_in?
    @images = @item.item_images.all
  end
  
  def complete
    @images = @item.item_images.all
  end

  def pay
    Payjp::Charge.create(
      amount: @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
      customer: @card.customer_id, #顧客ID
      currency: 'jpy', #日本円
      )
      # 購入者のidをDBに反映
      @item.update(buyer_id: current_user.id)

      redirect_to action: :complete
  end


  private

  def set_card
    @card = Card.where(user: current_user).first if Card.where(user: current_user).present?
  end

  def set_key  #秘密鍵の設定
    Payjp.api_key = Rails.application.credentials.payjp[:secret_key]
  end

  def retrieve_card  #登録されたカードから情報を引き出すメソッド
    if @card.present?
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_information = customer.cards.retrieve(@card.card_id)

      @card_brand = @card_information.brand
      case @card_brand
      when "Visa"
        @card_src = "card/visa.svg"
      when "JCB"
        @card_src = "card/jcb.svg"
      when "MasterCard"
        @card_src = "card/master-card.svg"
      when "American Express"
        @card_src = "card/american_express.svg"
      when "Diners Club"
        @card_src = "card/dinersclub.svg"
      when "Discover"
        @card_src = "card/discover.svg"
      end
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/cards_helper.rb
module CardsHelper
  def new
  end
end

app/views/cards/complete.html.haml
.main
  %header.confirmation-header
    = link_to root_path  do
      = image_tag 'logo/logo.png'
  %main.confirmation-body
    %section.confirmation-contents
      %h2.confirmation-contents__title 購入が完了しました
      %section.confirmation-contents__inner
        .confirmation-contents__inner-item
          .confirmation-contents__inner-item--image
            = image_tag @images[0].image.url
          .confirmation-contents__inner-item--detail
            %p.confirmation-contents__inner-item--detail-name
              = @item.name
            %p.confirmation-contents__inner-item--detail-price
              -# ↓場合分けあるいは計算するメソッドが必要?
              %span
                = "¥#{@item.price.to_s(:delimited)}"
              %span (税込)送料込み
      .complete-links
        .complete-links__top-page
          = link_to "トップページへ", root_path
        .complete-links__my-page
          = link_to "マイページへ", mypage_index_path
  = render partial: 'devise/footer'

app/views/cards/confirmation.haml
.main
  %header.confirmation-header
    = link_to root_path  do
      = image_tag 'logo/logo.png'
  %main.confirmation-body
    %section.confirmation-contents
      %h2.confirmation-contents__title 購入内容の確認
      %section.confirmation-contents__inner
        .confirmation-contents__inner-item
          .confirmation-contents__inner-item--image
            = image_tag @images[0].image.url
          .confirmation-contents__inner-item--detail
            %p.confirmation-contents__inner-item--detail-name
              = @item.name
            %p.confirmation-contents__inner-item--detail-price
              -# ↓場合分けあるいは計算するメソッドが必要?
              %span
                = "¥#{@item.price.to_s(:delimited)}"
              %span (税込)送料込み
      %section.confirmation-contents__inner
        .confirmation-contents__inner-buy
          .purchase-table
            .purchase-table__label 支払い金額
            .purchase-table__price
              = "¥#{@item.price.to_s(:delimited)}"
          - if @card.present?
            %section.pay-method
              .pay-method__inner
                %h3 支払い方法
                = link_to '変更する', cards_path, class:"change-cards"
                %p クレジットカード
                = image_tag @card_src, size: "35x25", alt: @card_brand, class: "card-information__image"
                %p
                  = "**** **** **** " + @card_information.last4
                  %br
                  - exp_month = @card_information.exp_month.to_s
                  - exp_year = @card_information.exp_year.to_s.slice(2,3)
                  = exp_month + " / " + exp_year
          - else
            %section.pay-method
              .pay-method__inner
                %h3 支払い方法
                = link_to new_card_path do
                  %p.pay-method__inner-registration
                    = fa_icon 'plus-circle'
                    %span.pay-method__inner-registration--text
                      登録してください
          %section.shipping-address
            .shipping-address__inner
              %h3 配送先
              -# ↓機能実装時にroot_pathを該当編集ページのパスに変更
              = link_to '変更する', root_path, class:"change-address"
            .shipping-address__inner-info
              %p
                = "〒 #{current_user.address[:post_cord].to_s.insert(3, "-")}"
                %br
                = current_user.address[:prefecture_id] + current_user.address[:city] + current_user.address[:address] + current_user.address[:building]
                %br
                = current_user.last_name + " " + current_user.first_name
          - if @card.present? && @item.buyer_id.blank?
            = form_tag(action: :pay, method: :post) do
              %button.purchase-btn-true{type:"submit"} 購入する
          - else
            %button.purchase-btn-false{type:"submit", disabled:""} お支払い方法を登録して下さい
  = render partial: 'devise/footer'

app/views/cards/index.html.haml
= render partial: "items/header"
- breadcrumb :method_payment
= render "layouts/breadcrumbs"
.wrapper__mypage
  = render partial: 'mypage/leftlist'
  .users-form 
    %h1 支払い方法
    .card-information
      - if @card.present?
        .card-information__title
          %h3 クレジットカード
        = form_with url: card_path(@card.id), method: :delete, local: true do |f|
          %figure
            = image_tag @card_src, size: "56x40", alt: @card_brand, class: "card-information__image"
          .card-information__number
            %p カード番号
            = "**** **** **** " + @card_information.last4
          .card-information__limit
            %p 有効期限(月/年)
            - exp_month = @card_information.exp_month.to_s
            - exp_year = @card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          %input{type: "hidden", name: "card_id", value: ""}
            = f.submit "削除する", class: "card-information__delete-btn"
= render partial: "items/aside"
= render partial: "items/footer"

app/views/cards/new.html.haml
= render partial: "items/header"
- breadcrumb :card_Registration
= render "layouts/breadcrumbs"
.wrapper__mypage
  = render partial: 'mypage/leftlist'
  .users-form 
    %h1 クレジットカード情報入力
    .information-content
      .user-informations
        = form_with url: cards_path, method: :post, html: { name: "inputForm" }, id: 'charge-form' do |f|
          .user-informations__card-number
            = f.label :カード番号, class: 'label'
            %span.form-required 必須
            = f.text_field :card_number, type: 'text', class: 'input-number', placeholder: '半角数字のみ', maxlength: "16"
            %ul.card-company
              %li.card-visa
                = image_tag("card/visa.svg" , size:"42x30")
              %li.card-master
                = image_tag("card/master-card.svg" , size:"42x30")
              %li.card-saison
                = image_tag("card/saison-card.svg" , size:"42x30")
              %li.card-jcb
                = image_tag("card/jcb.svg" , size:"42x30")
              %li.card-americanexpress
                = image_tag("card/american_express.svg" , size:"42x30")
              %li.card-diners
                = image_tag("card/dinersclub.svg" , size:"42x30")
              %li.card--discover
                = image_tag("card/discover.svg" , size:"42x30")
                
          .user-informations__expiration
            = f.label :有効期限, class: 'label'
            %span.form-required 必須
            .user-informations__expiration__select-month
              = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'input-expire'
              %span.month 月
              .user-informations__expiration__select__year
                = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'input-expire'
                %spam 年
                
            .user-informations__expiration__password
              = f.label :セキュリティコード, class: 'label'
              %span.form-required  必須
              = f.text_field :cvc, type: 'text', class: 'input-number', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4"
              .user-informations__expiration__card-back
                %span.question ?
                カードの裏面の番号とは？
              .user-informations__expiration__card-security#card
                %text カードの裏面をご参照ください。
                =image_tag("card/seq-card_3.png" , size:"240x105",)
            = f.submit '登録する', class: 'content-bottom--add-btn', id: 'token_submit'
= render partial: "items/aside"
= render partial: "items/footer"